[build]
  base = "Portfolio-main"
  publish = "Portfolio-main/frontend/build"
  command = "cd frontend && yarn install && yarn build"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"
  YARN_VERSION = "1.22.22"
  YARN_FLAGS = "--network-timeout 600000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
